# Generated by Django 3.2 on 2022-06-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220605_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish', 'title', 'status'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
