# Generated by Django 3.2 on 2022-07-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220701_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comemnts',
            new_name='Comments',
        ),
    ]
